### ISSUE TITLE
Scripts loaded on login page

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/files_rightclick#75]
We've found out that the files_rightclick scripts are loaded on every page, so even on the login page. However, it's not used there.

The problem is that in some scenarios the new JavaScript version is causing issue with the Nextcloud Outlook plugin because that uses IE as web engine for the login flow.

Would it be possible to only load this app's scripts for the files app, where it's actually used?

**Comment by danxuliu** [comment]
As far as I know this was addressed in #67, although it was not backported to _stable16_ (and it should not be backported yet because [it breaks the loading in the Files app](https://github.com/nextcloud/files_rightclick/pull/67#issuecomment-484003136)).

In any case, the problem with Internet Explorer 11 should have been fixed in #73 ;-)

**Comment by ChristophWurst** [comment]
Thanks! This will be fixed with 16.0.2 then, right?

**Comment by MorrisJobke** [comment]
> Thanks! This will be fixed with 16.0.2 then, right?

Yes.

**Comment by MorrisJobke** [comment]
> We've found out that the files_rightclick scripts are loaded on every page, so even on the login page. However, it's not used there.

Could be accomplished by using something like this: https://github.com/nextcloud/server/blob/41ef3d860cd1a565882cfd84dda72f2d9ad9cef2/apps/comments/lib/AppInfo/Application.php#L61-L66

**Comment by MorrisJobke** [comment]
cc @NastuzziSamy

**Comment by NastuzziSamy** [comment]
Was fixed in master
